name: kernel_build

on:
  workflow_dispatch:
    inputs:
      STRAT:
        description: 'STRAT'
        required: true
        default: 'strat'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v6
        with:
          root-reserve-mb: 1024
          swap-size-mb: 10240
          remove-dotnet: 'true'
          temp-reserve-mb: 1024
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Check Out
        uses: actions/checkout@v2

      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env

      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.build_sh }}" "build_sh config"
          required "${{ steps.config.outputs.branch_name }}" "BRANCH_NAME config"
          required "${{ steps.config.outputs.kernel_url }}" "KERNEL_URL config"
 
      - name: Clone 内核
        run: |
          ls -al
          cd /home/runner/work/action_build_kernel/action_build_kernel
          ls -al
          git clone "${{ steps.config.outputs.kernel_url }}" -b "${{ steps.config.outputs.branch_name }}" kernel
          df -h

      - name: 编译内核
        run: |
          sudo mv "${{ steps.config.outputs.build_sh }}" /home/runner/work/action_build_kernel/action_build_kernel/kernel
          cd /home/runner/work/action_build_kernel/action_build_kernel/kernel
          bash ./"${{ steps.config.outputs.build_sh }}"

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
         name: kernel
         path: kernel/out/arch/arm64/boot/Image
