name: kernel_build

on:
  workflow_dispatch:
    inputs:
      STRAT:
        description: 'STRAT'
        required: true
        default: 'strat'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v6
        with:
          root-reserve-mb: 1024
          swap-size-mb: 10240
          remove-dotnet: 'true'
          temp-reserve-mb: 1024
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Check Out
        uses: actions/checkout@v2

      - name: Prepare the environment
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo apt -y autoremove --purge
          sudo apt -y autoclean
          sudo apt clean
          sudo apt update
          sudo apt -y install git python python2 python3 gcc-aarch64-linux-gnu clang bc bison flex libssl-dev ccache 

      - name: 下载内核
        run: |
          cd /home/runner/work/
          git clone https://github.com/HK4567/android_kernel_xiaomi_gauguin.git -b Marshmallow-q1 kernel

      - name: 下载编译器
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang -b 20201017 clang
          ls -al clang/
          export
          
      - name: 编译内核
        run: |
          cd kernel/
          git submodule update --init --recursive
          export CLANG_PATH=/home/runner/work/clang
          export PATH=${CLANG_PATH}/bin:${PATH}
          export
          as -v
          make O=out \
                ARCH=arm64 \
                CC=${CLANG_PATH}/bin/clang \
                CLANG_TRIPLE=aarch64-linux-gnu- \
                CROSS_COMPILE=${CLANG_PATH}/bin/aarch64-linux-gnu- \
                gauguin_user_defconfig
          echo "-------------------------------------------------------------------------------------------"
          echo "-------------------------------------------------------------------------------------------"
          make O=out \
                ARCH=arm64 \
                CC=${CLANG_PATH}/bin/clang \
                CLANG_TRIPLE=aarch64-linux-gnu- \
                CROSS_COMPILE=${CLANG_PATH}/bin/aarch64-linux-gnu- \
                -j4 2>&1 | tee out/kernel.log
          

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
         name: kernel
         path: kernel/out/arch/arm64/boot/Image
