name: kernel_build

on:
  workflow_dispatch:
    inputs:
      STRAT:
        description: 'STRAT'
        required: true
        default: 'strat'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v6
        with:
          root-reserve-mb: 1024
          swap-size-mb: 10240
          remove-dotnet: 'true'
          temp-reserve-mb: 1024
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Check Out
        uses: actions/checkout@v2

      - name: Prepare the environment
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo apt -y autoremove --purge
          sudo apt -y autoclean
          sudo apt clean
          sudo apt update
          sudo apt -y install git python python2 python3 gcc-aarch64-linux-gnu- clang bc bison flex libssl-dev ccache 

      - name: Clone 内核
        run: |
          ls -al
          cd /home/runner/work/action_build_kernel/action_build_kernel
          ls -al
          git clone https://github.com/HK4567/android_kernel_xiaomi_gauguin.git -b Marshmallow-q1 kernel
          git clone --depth=1 https://github.com/kdrag0n/proton-clang -b 20201017 /home/runner/work/clang
          chmod -R 777 /home/runner/work/clang
          
          
          
      - name: 编译内核
        run: |
          cd kernel/
          git submodule update --init --recursive
          export ARCH=arm64
          export SUBARCH=arm64
          make O=out CC=/home/runner/work/clang/bin/clang-12 CROSS_COMPILE=/home/runner/work/clang/bin/aarch64-linux-gnu- gauguin_user_defconfig
          make O=out CC=/home/runner/work/clang/bin/clang-12 CROSS_COMPILE=/home/runner/work/clang/bin/aarch64-linux-gnu- -j4 2>&1 | tee out/kernel.log
          

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
         name: kernel
         path: kernel/out/arch/arm64/boot/Image
