name: action_kernel

on:
  watch:
    types: [started]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
   
env:
  repo_url: https://github.com/meizucustoms/android_kernel_meizu_sdm845
  repo_branch: oreo
  build_sh: gcc4.9.sh
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
 
      - name: Git kernel
        run: |
          git clone $repo_url -b $repo_branch kernel

      - name: make kernel
        run: |
          sudo mv build.sh $GITHUB_WORKSPACE/kernel
          cd $GITHUB_WORKSPACE/kernel
          bash ./$build_sh

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "kernel/out/arch/arm64/boot/Image.gz-dtb"


